name: Lint Commit Messages
on: pull_request

jobs:
  commitlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5.4.5
