name: ShellCheck
on: pull_request

jobs:
  shellcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: ludeeus/action-shellcheck@master
